# Generated by Django 5.0.6 on 2024-06-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='cars_value',
            new_name='cars_price',
        ),
    ]
